# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "goals", :force => true do |t|
    t.column "user_id",  :integer
    t.column "variable", :string
    t.column "amount",   :float
    t.column "end_date", :datetime
    t.column "notes",    :text
  end

  create_table "nudges", :force => true do |t|
    t.column "created_at", :datetime
    t.column "user_id",    :integer
    t.column "message",    :string
  end

  create_table "tweets", :force => true do |t|
    t.column "sent_at",    :datetime
    t.column "sender_id",  :integer
    t.column "user_id",    :integer
    t.column "tweet_id",   :integer
    t.column "raw_text",   :string
    t.column "created_at", :datetime
  end

  create_table "updates", :force => true do |t|
    t.column "variable",   :string
    t.column "value",      :float
    t.column "tweet_id",   :integer
    t.column "user_id",    :integer
    t.column "created_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "screen_name",     :string
    t.column "twitter_id",      :integer
    t.column "openid_url",      :string
    t.column "alert_address",   :string
    t.column "nudge_frequency", :integer
  end

end
